l1=[1]
n=7
for i in range(0,n):
    #print(l1)
    l2=[]
    j=0
    c1=1
    if(len(l1)>1):
        while(j<len(l1)):
            if(j==(len(l1)-1) and l1[j]!=l1[j-1]):
                l2.append(c1)
                l2.append(l1[j])
                j+=1
            elif(j!=(len(l1)-1)):
                k=j+1
                #print(j,k)
                while(k<len(l1)):
                    if(k!=(len(l1)-1)):
                        if(l1[j]==l1[k]):
                            c1+=1
                            k+=1
                        else:
                            l2.append(c1)
                            l2.append(l1[j])
                            c1=1
                            j=k
                            k+=1                      
                            break
                    elif(k==(len(l1)-1) and c1>1):
                        if(l1[j]==l1[k]):
                            c1+=1
                            l2.append(c1)
                            l2.append(l1[j])
                        else:
                            l2.append(c1)
                            l2.append(l1[j])
                            l2.append(1)
                            l2.append(l1[k])
                        k+=1
                        j=k
                        break
                    else:
                        if(l1[j]==l1[k]):
                            c1+=1
                            l2.append(c1)
                            l2.append(l1[j])
                        else:
                            l2.append(1)
                            l2.append(l1[j])
                            l2.append(1)
                            l2.append(l1[k])
                        k+=1
                        j=k
                        break
            elif(j==(len(l1)-1) and l1[j]==l1[j-1]):
                j+=1
                break
    else:
        l2.append(c1)
        l2.append(l1[0])
        c1=1
    print(l2)
    l1=l2